### Assignment 1 – Data Wrangling Using Pandas

In this assignment we are going to analyze a web log file. Read this article for description about a typical web log file: https://en.wikipedia.org/wiki/Common_Log_Format). We need to clean/parse the log file to convert them into a proper tabular format

1.      In the first part of this assignment, you need to understand the structure of each log and use regular expression to parse the data

#### Write a regular expression to convert the data in a structured o/p (sample o/p shown below)

In [6]:
import pandas as pd
import re

#df = pd.read_csv(r'access_log_Jul95.txt', sep='\ (?!-)(?!\s*\S+")(?!\s+)', engine="python")
#df = pd.read_csv(r'access_log_Jul95.txt', sep='\ (?=\[)|(?<="\w)\s|\s(?=\/)|(?<=\])\ |(?<=")\ |(?<=\d)\ (?=\d)', engine="python")


df = pd.read_csv(r'access_log_Jul95.txt', sep='\ (?=\[)|(?<="\w\w\w)\s(?=\/)|(?<="\w\w\w\w)\s(?=\/)|(?<="\w\w\w\w\w)\s(?=\/)|(?<=\])\ |(?<=")\ |(?<=\d)\ (?=\d)', engine="python", header=None)

In [8]:
df.columns = ['host', 'time', 'request_type', 'url', 'response', 'size']

In [9]:
df

,host,time,request_type,url,response,size
0,199.72.81.55 - -,[01/Jul/1995:00:00:01 -0400],"""GET","/history/apollo/ HTTP/1.0""",200,6245.0
1,unicomp6.unicomp.net - -,[01/Jul/1995:00:00:06 -0400],"""GET","/shuttle/countdown/ HTTP/1.0""",200,3985.0
2,199.120.110.21 - -,[01/Jul/1995:00:00:09 -0400],"""GET",/shuttle/missions/sts-73/mission-sts-73.html H...,200,4085.0
3,burger.letters.com - -,[01/Jul/1995:00:00:11 -0400],"""GET","/shuttle/countdown/liftoff.html HTTP/1.0""",304,0.0
4,199.120.110.21 - -,[01/Jul/1995:00:00:11 -0400],"""GET",/shuttle/missions/sts-73/sts-73-patch-small.gi...,200,4179.0
...,...,...,...,...,...,...
91709,ix-tam3-07.ix.netcom.com - -,[02/Jul/1995:13:40:05 -0400],"""GET","/icons/blank.xbm HTTP/1.0""",200,509.0
91710,csd1-9.infolink.net - -,[02/Jul/1995:13:40:06 -0400],"""GET","/procurement/business/kscbus.htm HTTP/1.0""",200,1293.0
91711,port49.iprolink.ch - -,[02/Jul/1995:13:40:07 -0400],"""GET",/shuttle/missions/sts-71/sts-71-day-06-highlig...,200,6136.0
91712,che2.llnl.gov - -,[02/Jul/1995:13:40:07 -0400],"""GET","/shuttle/missions/sts-7/images/ HTTP/1.0""",200,1313.0
91713,ix-tam3-07.ix.netcom.com - -,[02/Jul/1995:13:40:07 -0400],"""GET","/icons/menu.xbm HTTP/1.0""",200,527.0

In [10]:
df['request_type'] = df['request_type'].str.replace(r'"', '', regex=True)

In [21]:
df['url'] = df['url'].str.replace(r'"', '', regex=True)
df['host'] = df['host'].str.replace(r'(?<=\S)\ +.*', '', regex=True)
df['time'] = df['time'].str.replace(r'[\[\]]', '', regex=True)
df['time_r'] = pd.to_datetime(df['time'], format='%d/%b/%Y:%H:%M:%S %z', utc=True)

AttributeError: Can only use .str accessor with string values!

In [22]:
df

,host,time,request_type,url,response,size
0,199.72.81.55,1995-07-01 04:00:01+00:00,GET,/history/apollo/ HTTP/1.0,200,6245.0
1,unicomp6.unicomp.net,1995-07-01 04:00:06+00:00,GET,/shuttle/countdown/ HTTP/1.0,200,3985.0
2,199.120.110.21,1995-07-01 04:00:09+00:00,GET,/shuttle/missions/sts-73/mission-sts-73.html H...,200,4085.0
3,burger.letters.com,1995-07-01 04:00:11+00:00,GET,/shuttle/countdown/liftoff.html HTTP/1.0,304,0.0
4,199.120.110.21,1995-07-01 04:00:11+00:00,GET,/shuttle/missions/sts-73/sts-73-patch-small.gi...,200,4179.0
...,...,...,...,...,...,...
91709,ix-tam3-07.ix.netcom.com,1995-07-02 17:40:05+00:00,GET,/icons/blank.xbm HTTP/1.0,200,509.0
91710,csd1-9.infolink.net,1995-07-02 17:40:06+00:00,GET,/procurement/business/kscbus.htm HTTP/1.0,200,1293.0
91711,port49.iprolink.ch,1995-07-02 17:40:07+00:00,GET,/shuttle/missions/sts-71/sts-71-day-06-highlig...,200,6136.0
91712,che2.llnl.gov,1995-07-02 17:40:07+00:00,GET,/shuttle/missions/sts-7/images/ HTTP/1.0,200,1313.0
91713,ix-tam3-07.ix.netcom.com,1995-07-02 17:40:07+00:00,GET,/icons/menu.xbm HTTP/1.0,200,527.0